class Settings:
    def Dir_RMAQ(): return 'sqlite:///lib/RMAQ.db'
    def Dir_CBDR(): return 'sqlite:///lib/CBDR.db'
    def Dir_BDR(): return 'sqlite:///lib/BDR.db'
    def Dir_PBDR(): return 'sqlite:///lib/PBDR.db'
    def Dir_CBD(): return 'sqlite:///lib/CBD.db'
    def Dir_OP(): return 'sqlite:///lib/OP.db'
    def Dir_PW(): return 'sqlite:///lib/PW.db'
    def Dir_Inf(): return 'sqlite:///lib/Inf.db'
    def Dir_CN(): return 'sqlite:///lib/CN.db'
    def Dir_REFE(): return 'sqlite:///lib/REFE.db'
    def Dir_BD(): return 'sqlite:///lib/BD.db'
    def Dir_PBD(): return 'sqlite:///lib/PBD.db'
    def Dir_PBDP(): return 'sqlite:///lib/PBDP.db'
    def Dir_BDP(): return 'sqlite:///lib/BDP.db'
    def Dir_CBDP(): return 'sqlite:///lib/CBDP.db'
    def Dir_BDA(): return 'sqlite:///lib/BDAdb'
    def Dir_PBDA(): return 'sqlite:///lib/PBDA.db'
    def Dir_CBDA(): return 'sqlite:///lib/CBDA.db'
    def Dir_REFEP(): return 'sqlite:///lib/REFEP.db'
    def Dir_Cl(): return 'sqlite:///lib/Cl.db'
    def Dir_CCl(): return 'sqlite:///lib/CCl.db'

    def Var_EC(): return 'ENKA CAJA'
    def Var_EE(): return 'ENKA ESTIBAS'
    def Var_IC(): return 'IMPORTADOS CAJA'
    def Var_IE(): return 'IMPORTADOS ESTIBAS'

    def Var_P1(): return 'CAJAS'
    def Var_P2(): return 'ESTIBAS'

    def Var_Process1(): return 'NORMAL'
    def Var_Process2(): return 'PRUEBA'

    def Var_Provider1(): return 'ENKA'
    def Var_Provider2(): return 'IMPORTADOS'

    def Dir_Send1(): return 'lib/CBDR.db'
    def Dir_Send2(): return 'lib/RMAQ.db'
    def Dir_Send3(): return 'lib/PW.db'
    def Dir_Send4(): return 'lib/OP.db'
    def Dir_Send5(): return 'lib/CBD.db'
    def Dir_Dest1(): return '/BaseDatosRetorcido.db'
    def Dir_Dest2(): return '/RefereneciaMaquinas.db'
    def Dir_Dest3(): return '/Password.db'
    def Dir_Dest4(): return '/Operarios.db'
    def Dir_Dest5(): return '/BaseDatosRecepcionMateriaPrima.db'

    def Var_Comp1(): return 'CODIGO DE BARRAS'
    def Var_Comp2(): return 'NUMERO DE REMISION'
    def Var_Comp3(): return 'NUMERO DE PRESENTACION'
    def Var_Comp4(): return 'PESO TOTAL'
    def Var_Comp5(): return 'PESO RETIRADO'
    def Var_Comp6(): return 'NUMERO DE BOBINAS'
    def Var_Comp7(): return 'NUMERO DE BOBINAS RETIRADAS'
    def Var_Comp8(): return 'PESO NETO'
    def Var_Comp9(): return 'NUMERO DE RECEPCION'
    def Var_Comp10(): return 'MAQUINA'
    def Var_Comp11(): return 'ESTADO'
    def Var_Comp12(): return 'PRESENTACION'
    def Var_Comp13(): return 'REFERENCIA'
    def Var_Comp14(): return 'PROVEEDOR'
    def Var_Comp15(): return 'OPERADOR'
    def Var_Comp16(): return 'VAPORIZADO'
    def Var_Comp17(): return 'DESPERDICIO'
    def Var_Comp18(): return 'CANTIDAD DE BOTELLAS'
    def Var_Comp19(): return 'FECHA DE INICIO'
    def Var_Comp20(): return 'FECHA FINAL'
    def Var_Comp21(): return 'LOTE'
    def Var_Comp22(): return 'CODIGO DE COLORES'
    def Var_Comp23(): return 'REFERENCIA DE HILO'
    def Var_Comp24(): return 'ID'
    def Var_Comp25(): return 'PARO'
    def Var_Comp26(): return 'REF2'
    def Var_Comp27(): return 'PESO TARA'
    def Var_Comp28(): return 'PESO DESPERDICIO'
    def Var_Comp29(): return 'PESO DESPERDICIO TARA'
    def Var_Comp30(): return 'PARO'
    def Var_Comp31(): return 'TOTAL'
    def Var_Comp32(): return 'UNIDAD DE MEDIDA'
    def Var_Comp33(): return 'RAZON DE PARO'
    def Var_Comp34(): return 'NUMERO DE PUESTOS'
    def Var_Comp35(): return 'NUMERO DE ORDEN'
    def Var_Comp36(): return 'NUMERO DE ITEM'
    def Var_Comp37(): return 'TELEFONO'
    def Var_Comp38(): return 'CLIENTE'
    def Var_Comp39(): return 'CANTIDAD DE PEDIDO'
    def Var_Comp40(): return 'DISPONIBILIDAD'
    def Var_Comp41(): return 'DESPACHADO'
    def Var_Comp42(): return 'MATERIAL'
    def Var_Comp43(): return 'DIAMETRO'
    def Var_Comp44(): return 'NUMERO DE MALLAS'
    def Var_Comp45(): return 'CODIGO'
    def Var_Comp46(): return 'TIPO DE PRESENTACION'
    def Var_Comp47(): return 'CANTIDAD DE DISPONIBLE'
    def Var_Comp48(): return 'CANTIDAD RETIRADO'
    def Var_Comp49(): return 'CANTIDAD DE LOTE'
    def Var_Comp50(): return 'TIPO DE PRODUCTO'

    def Var_Find1(): return 'RFID'
    def Var_Find2(): return 'BASCULA'
    def Var_Find3(): return 'PERMITION'

    def Var_PP(): return 'PARO DE PROCESO'
    def Var_PM(): return 'PARO DE MONTAJE'

    def Var_MR(): return 'MONTAJE DE RETORCIDO'
    def Var_PR(): return 'PROCESO DE RETORCIDO'

    def Var_MC(): return 'MULTIFILAMENTO C'
    def Var_RM(): return 'REDES DE MONOFILAMENTO'
    def Var_AMC(): return 'ALMACEN DE MULTIFILAMENTO C'
    def Var_ARM(): return 'ALMACEN DE REDES DE MONOFILAMENTO'
    def Var_AA(): return 'ALMACEN DE ALMACENAMIENTO'
    def Var_AAR(): return 'ALMACEN DE ALMACENAMIENTO RETIRADO'
    def Var_IN(): return 'ALMACENAMIENTO'
    def Var_OUT(): return 'RETIRO DE ALMACEN'

    def PRO1(): return 'PROCESO DE RECEPCION DE MATERIA PRIMA'
    def PRO2(): return 'PROCESO DE RECEPCION DE PEDIDO'
    def PRO3(): return 'PROCESO DE RETORCIDO'
    def PRO4(): return 'PROCESO DE ALMACENAMIENTO'

    def PP(): return 'MEDEJAS'
    def PP2(): return 'CONOS'
    def PP3(): return 'BOBINAS'

    def ACC(): return 'ACCESO TOTAL'
    def ACC2(): return 'ACCESO AL PROGRAMA'

    def PR(): return 'NUEVO PROCESO'
    def PR2(): return 'PROCESO'