class SettingsUs:
    def Var_KNOW(): return ('NO ENCONTRADO', 0)
    def Ref_User1(): return 'CEDULA'
    def Ref_User2(): return 'NOMBRE'
    def Ref_User3(): return 'PERMISO 1'
    def Ref_User4(): return 'PERMISO 2'
    def Ref_User5(): return 'PERMISO 3'
    def Ref_User6(): return 'PERMISO 4'
    def Ref_User7(): return 'PERMISO 5'
    def Ref_User8(): return 'PERMISO 6'
    def Ref_User9(): return 'PERMISO 7'
    def Ref_User10(): return 'PERMISO 8'
    def Ref_User11(): return 'PERMISO 9'
    def Ref_User12(): return 'PERMISO 10'
    def Ref_User13(): return 'GENERO'
    def Ref_User14(): return 'AREA DE TRABAJO'
    def Ref_User15(): return 'POSICION DE TRABAJO'
    def Ref_User16(): return 'CUMPLEAÑOS'
    def Ref_User17(): return 'TIPO DE SANGRE'
    def Ref_User18(): return 'GRADO ESCOLARIDAD'
    def Ref_User19(): return 'PROFESION'
    def Ref_User20(): return 'TELEFONO'
    def Ref_User21(): return 'CELULAR'
    def Ref_User22(): return 'EPS'
    def Ref_User23(): return 'ARL'
    def Ref_User24(): return 'PENSION'
    def Ref_User25(): return 'DIRECCION'
    def Ref_User26(): return 'BARRIO'
    def Ref_User27(): return 'MUNICIPIO'
    def Ref_User28(): return 'ESTRATO SOCIOECONOMICO'
    def Ref_User29(): return 'EMAIL'
    def Ref_User30(): return 'NOMBRE CONYUGE'
    def Ref_User31(): return 'TELEFONO CONYUGE'
    def Ref_User32(): return 'CELULAR CONYUGE'
    def Ref_User33(): return 'NOMBRES DE HIJOS'
    def Ref_User34(): return 'PNA DE EMERGENCIA'
    def Ref_User35(): return 'TELEFONO DEL PNA'
    def Ref_User36(): return 'POLIZA'
    def Ref_User37(): return 'VIVIENDA'
    def Ref_User38(): return 'GUSTOS'
    def Ref_User39(): return 'ALTURA'
    def Ref_User40(): return 'PESO'
    def Ref_User41(): return 'FUMA'
    def Ref_User42(): return 'BEBE'
    def Ref_User43(): return 'ENFERMEDAD'
    def Ref_User44(): return 'TALLA DE CAMISA'
    def Ref_User45(): return 'TALLA DE PANTALON'
    def Ref_User46(): return 'TALLA DE ZAPATOS'
    def Ref_User47(): return 'CURSO DE ALTURAS'
    def Ref_User48(): return 'CERTIFICADO DE ALTURAS'